#!/bin/bash
#
# Get INSTALL AND CONFIGURE Jenkins on REDHAT 7
#
# Based on a bash script by Saddam ZEMMALI - 10/11/2017 
#
# Author = Saddam ZEMMALI - 10/11/2017 

# cat /etc/resolv.conf
# Generated by NetworkManager
echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

echo "Install last EPEL Repo"
yum -y localinstall https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

yum -y update
yum clean expire-cache

# How to install Jenkins on RedHat 7
wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
yum install jenkins

echo "Install JAVA"
sudo yum install java-1.8.0-openjdk.x86_64
java -version

echo $JAVA_HOME
echo $JRE_HOME

cp /etc/profile /etc/profile_backup
ll /usr/lib/jvm/jre-1.8.0-openjdk

echo 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | sudo tee -a /etc/profile
ll /usr/lib/jvm/jre
echo 'export JRE_HOME=/usr/lib/jvm/jre' | sudo tee -a /etc/profile

source /etc/profile
echo $JAVA_HOME
echo $JRE_HOME

echo "Start Jenkins Service Using Systemd"
sudo systemctl start jenkins.service

echo "Enable Jenkins Service Using Systemd"
sudo systemctl enable jenkins.service

netstat -ntlp | grep 8080

echo "Add New Rule to Firewalld"
sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp
sudo firewall-cmd --reload
firewall-cmd --list-all
systemctl stop firewalld.service
systemctl disable firewalld.service

cat /var/lib/jenkins/secrets/initialAdminPassword
